CREATE TABLE city (
                      id integer NOT NULL PRIMARY KEY AUTO_INCREMENT,
                      name text NOT NULL,
                      countrycode character(3) NOT NULL,
                      district text NOT NULL,
                      population integer NOT NULL
);

CREATE TABLE country (
                         code character(3) NOT NULL PRIMARY KEY,
                         name text NOT NULL,
                         continent text NOT NULL,
                         region text NOT NULL,
                         surfacearea real NOT NULL,
                         indepyear smallint,
                         population integer NOT NULL,
                         lifeexpectancy real,
                         gnp numeric(10,2),
                         gnpold numeric(10,2),
                         localname text NOT NULL,
                         governmentform text NOT NULL,
                         headofstate text,
                         capital integer,
                         code2 character(2) NOT NULL,
                         CONSTRAINT country_continent_check CHECK ((((((((continent = 'Asia'::text) OR (continent = 'Europe'::text)) OR (continent = 'North America'::text)) OR (continent = 'Africa'::text)) OR (continent = 'Oceania'::text)) OR (continent = 'Antarctica'::text)) OR (continent = 'South America'::text)))
);

CREATE TABLE countrylanguage (
                                 countrycode character(3) NOT NULL,
                                 language varchar(255) NOT NULL,
                                 isofficial boolean NOT NULL,
                                 percentage real NOT NULL,
                                 PRIMARY KEY(countrycode, language)
);

--
-- Insert cities.
--

INSERT INTO city (id, name, countrycode, district, population) VALUES (1, 'Kabul', 'AFG', 'Kabol', 1780000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (2, 'Qandahar', 'AFG', 'Qandahar', 237500);
INSERT INTO city (id, name, countrycode, district, population) VALUES (3, 'Herat', 'AFG', 'Herat', 186800);
INSERT INTO city (id, name, countrycode, district, population) VALUES (4, 'Mazar-e-Sharif', 'AFG', 'Balkh', 127800);
INSERT INTO city (id, name, countrycode, district, population) VALUES (5, 'Amsterdam', 'NLD', 'Noord-Holland', 731200);
INSERT INTO city (id, name, countrycode, district, population) VALUES (6, 'Rotterdam', 'NLD', 'Zuid-Holland', 593321);
INSERT INTO city (id, name, countrycode, district, population) VALUES (7, 'Haag', 'NLD', 'Zuid-Holland', 440900);
INSERT INTO city (id, name, countrycode, district, population) VALUES (8, 'Utrecht', 'NLD', 'Utrecht', 234323);
INSERT INTO city (id, name, countrycode, district, population) VALUES (9, 'Eindhoven', 'NLD', 'Noord-Brabant', 201843);
INSERT INTO city (id, name, countrycode, district, population) VALUES (10, 'Tilburg', 'NLD', 'Noord-Brabant', 193238);
INSERT INTO city (id, name, countrycode, district, population) VALUES (11, 'Groningen', 'NLD', 'Groningen', 172701);
INSERT INTO city (id, name, countrycode, district, population) VALUES (12, 'Breda', 'NLD', 'Noord-Brabant', 160398);
INSERT INTO city (id, name, countrycode, district, population) VALUES (13, 'Apeldoorn', 'NLD', 'Gelderland', 153491);
INSERT INTO city (id, name, countrycode, district, population) VALUES (14, 'Nijmegen', 'NLD', 'Gelderland', 152463);
INSERT INTO city (id, name, countrycode, district, population) VALUES (15, 'Enschede', 'NLD', 'Overijssel', 149544);
INSERT INTO city (id, name, countrycode, district, population) VALUES (16, 'Haarlem', 'NLD', 'Noord-Holland', 148772);
INSERT INTO city (id, name, countrycode, district, population) VALUES (17, 'Almere', 'NLD', 'Flevoland', 142465);
INSERT INTO city (id, name, countrycode, district, population) VALUES (18, 'Arnhem', 'NLD', 'Gelderland', 138020);
INSERT INTO city (id, name, countrycode, district, population) VALUES (19, 'Zaanstad', 'NLD', 'Noord-Holland', 135621);
INSERT INTO city (id, name, countrycode, district, population) VALUES (20, 'Â´s-Hertogenbosch', 'NLD', 'Noord-Brabant', 129170);
INSERT INTO city (id, name, countrycode, district, population) VALUES (21, 'Amersfoort', 'NLD', 'Utrecht', 126270);
INSERT INTO city (id, name, countrycode, district, population) VALUES (22, 'Maastricht', 'NLD', 'Limburg', 122087);
INSERT INTO city (id, name, countrycode, district, population) VALUES (23, 'Dordrecht', 'NLD', 'Zuid-Holland', 119811);
INSERT INTO city (id, name, countrycode, district, population) VALUES (24, 'Leiden', 'NLD', 'Zuid-Holland', 117196);
INSERT INTO city (id, name, countrycode, district, population) VALUES (25, 'Haarlemmermeer', 'NLD', 'Noord-Holland', 110722);
INSERT INTO city (id, name, countrycode, district, population) VALUES (26, 'Zoetermeer', 'NLD', 'Zuid-Holland', 110214);
INSERT INTO city (id, name, countrycode, district, population) VALUES (27, 'Emmen', 'NLD', 'Drenthe', 105853);
INSERT INTO city (id, name, countrycode, district, population) VALUES (28, 'Zwolle', 'NLD', 'Overijssel', 105819);
INSERT INTO city (id, name, countrycode, district, population) VALUES (29, 'Ede', 'NLD', 'Gelderland', 101574);
INSERT INTO city (id, name, countrycode, district, population) VALUES (30, 'Delft', 'NLD', 'Zuid-Holland', 95268);
INSERT INTO city (id, name, countrycode, district, population) VALUES (31, 'Heerlen', 'NLD', 'Limburg', 95052);
INSERT INTO city (id, name, countrycode, district, population) VALUES (32, 'Alkmaar', 'NLD', 'Noord-Holland', 92713);
INSERT INTO city (id, name, countrycode, district, population) VALUES (33, 'Willemstad', 'ANT', 'CuraÃ§ao', 2345);
INSERT INTO city (id, name, countrycode, district, population) VALUES (34, 'Tirana', 'ALB', 'Tirana', 270000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (35, 'Alger', 'DZA', 'Alger', 2168000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (36, 'Oran', 'DZA', 'Oran', 609823);
INSERT INTO city (id, name, countrycode, district, population) VALUES (37, 'Constantine', 'DZA', 'Constantine', 443727);
INSERT INTO city (id, name, countrycode, district, population) VALUES (38, 'Annaba', 'DZA', 'Annaba', 222518);
INSERT INTO city (id, name, countrycode, district, population) VALUES (39, 'Batna', 'DZA', 'Batna', 183377);
INSERT INTO city (id, name, countrycode, district, population) VALUES (40, 'SÃ©tif', 'DZA', 'SÃ©tif', 179055);
INSERT INTO city (id, name, countrycode, district, population) VALUES (41, 'Sidi Bel AbbÃ¨s', 'DZA', 'Sidi Bel AbbÃ¨s', 153106);
INSERT INTO city (id, name, countrycode, district, population) VALUES (42, 'Skikda', 'DZA', 'Skikda', 128747);
INSERT INTO city (id, name, countrycode, district, population) VALUES (43, 'Biskra', 'DZA', 'Biskra', 128281);
INSERT INTO city (id, name, countrycode, district, population) VALUES (44, 'Blida (el-Boulaida)', 'DZA', 'Blida', 127284);
INSERT INTO city (id, name, countrycode, district, population) VALUES (45, 'BÃ©jaÃ¯a', 'DZA', 'BÃ©jaÃ¯a', 117162);
INSERT INTO city (id, name, countrycode, district, population) VALUES (46, 'Mostaganem', 'DZA', 'Mostaganem', 115212);
INSERT INTO city (id, name, countrycode, district, population) VALUES (47, 'TÃ©bessa', 'DZA', 'TÃ©bessa', 112007);
INSERT INTO city (id, name, countrycode, district, population) VALUES (48, 'Tlemcen (Tilimsen)', 'DZA', 'Tlemcen', 110242);
INSERT INTO city (id, name, countrycode, district, population) VALUES (49, 'BÃ©char', 'DZA', 'BÃ©char', 107311);
INSERT INTO city (id, name, countrycode, district, population) VALUES (50, 'Tiaret', 'DZA', 'Tiaret', 100118);
INSERT INTO city (id, name, countrycode, district, population) VALUES (51, 'Ech-Chleff (el-Asnam)', 'DZA', 'Chlef', 96794);
INSERT INTO city (id, name, countrycode, district, population) VALUES (52, 'GhardaÃ¯a', 'DZA', 'GhardaÃ¯a', 89415);
INSERT INTO city (id, name, countrycode, district, population) VALUES (53, 'Tafuna', 'ASM', 'Tutuila', 5200);
INSERT INTO city (id, name, countrycode, district, population) VALUES (54, 'Fagatogo', 'ASM', 'Tutuila', 2323);
INSERT INTO city (id, name, countrycode, district, population) VALUES (55, 'Andorra la Vella', 'AND', 'Andorra la Vella', 21189);
INSERT INTO city (id, name, countrycode, district, population) VALUES (56, 'Luanda', 'AGO', 'Luanda', 2022000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (57, 'Huambo', 'AGO', 'Huambo', 163100);
INSERT INTO city (id, name, countrycode, district, population) VALUES (58, 'Lobito', 'AGO', 'Benguela', 130000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (59, 'Benguela', 'AGO', 'Benguela', 128300);
INSERT INTO city (id, name, countrycode, district, population) VALUES (60, 'Namibe', 'AGO', 'Namibe', 118200);
INSERT INTO city (id, name, countrycode, district, population) VALUES (61, 'South Hill', 'AIA', 'Â–', 961);
INSERT INTO city (id, name, countrycode, district, population) VALUES (62, 'The Valley', 'AIA', 'Â–', 595);
INSERT INTO city (id, name, countrycode, district, population) VALUES (63, 'Saint JohnÂ´s', 'ATG', 'St John', 24000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (64, 'Dubai', 'ARE', 'Dubai', 669181);
INSERT INTO city (id, name, countrycode, district, population) VALUES (65, 'Abu Dhabi', 'ARE', 'Abu Dhabi', 398695);
INSERT INTO city (id, name, countrycode, district, population) VALUES (66, 'Sharja', 'ARE', 'Sharja', 320095);
INSERT INTO city (id, name, countrycode, district, population) VALUES (67, 'al-Ayn', 'ARE', 'Abu Dhabi', 225970);
INSERT INTO city (id, name, countrycode, district, population) VALUES (68, 'Ajman', 'ARE', 'Ajman', 114395);
INSERT INTO city (id, name, countrycode, district, population) VALUES (69, 'Buenos Aires', 'ARG', 'Distrito Federal', 2982146);
INSERT INTO city (id, name, countrycode, district, population) VALUES (70, 'La Matanza', 'ARG', 'Buenos Aires', 1266461);
INSERT INTO city (id, name, countrycode, district, population) VALUES (71, 'CÃ³rdoba', 'ARG', 'CÃ³rdoba', 1157507);
INSERT INTO city (id, name, countrycode, district, population) VALUES (72, 'Rosario', 'ARG', 'Santa FÃ©', 907718);
INSERT INTO city (id, name, countrycode, district, population) VALUES (73, 'Lomas de Zamora', 'ARG', 'Buenos Aires', 622013);
INSERT INTO city (id, name, countrycode, district, population) VALUES (74, 'Quilmes', 'ARG', 'Buenos Aires', 559249);
INSERT INTO city (id, name, countrycode, district, population) VALUES (75, 'Almirante Brown', 'ARG', 'Buenos Aires', 538918);
INSERT INTO city (id, name, countrycode, district, population) VALUES (76, 'La Plata', 'ARG', 'Buenos Aires', 521936);
INSERT INTO city (id, name, countrycode, district, population) VALUES (77, 'Mar del Plata', 'ARG', 'Buenos Aires', 512880);
INSERT INTO city (id, name, countrycode, district, population) VALUES (78, 'San Miguel de TucumÃ¡n', 'ARG', 'TucumÃ¡n', 470809);
INSERT INTO city (id, name, countrycode, district, population) VALUES (79, 'LanÃºs', 'ARG', 'Buenos Aires', 469735);
INSERT INTO city (id, name, countrycode, district, population) VALUES (80, 'Merlo', 'ARG', 'Buenos Aires', 463846);
INSERT INTO city (id, name, countrycode, district, population) VALUES (81, 'General San MartÃ­n', 'ARG', 'Buenos Aires', 422542);
INSERT INTO city (id, name, countrycode, district, population) VALUES (82, 'Salta', 'ARG', 'Salta', 367550);
INSERT INTO city (id, name, countrycode, district, population) VALUES (83, 'Moreno', 'ARG', 'Buenos Aires', 356993);
INSERT INTO city (id, name, countrycode, district, population) VALUES (84, 'Santa FÃ©', 'ARG', 'Santa FÃ©', 353063);
INSERT INTO city (id, name, countrycode, district, population) VALUES (85, 'Avellaneda', 'ARG', 'Buenos Aires', 353046);
INSERT INTO city (id, name, countrycode, district, population) VALUES (86, 'Tres de Febrero', 'ARG', 'Buenos Aires', 352311);
INSERT INTO city (id, name, countrycode, district, population) VALUES (87, 'MorÃ³n', 'ARG', 'Buenos Aires', 349246);
INSERT INTO city (id, name, countrycode, district, population) VALUES (88, 'Florencio Varela', 'ARG', 'Buenos Aires', 315432);
INSERT INTO city (id, name, countrycode, district, population) VALUES (89, 'San Isidro', 'ARG', 'Buenos Aires', 306341);
INSERT INTO city (id, name, countrycode, district, population) VALUES (90, 'Tigre', 'ARG', 'Buenos Aires', 296226);
INSERT INTO city (id, name, countrycode, district, population) VALUES (91, 'Malvinas Argentinas', 'ARG', 'Buenos Aires', 290335);
INSERT INTO city (id, name, countrycode, district, population) VALUES (92, 'Vicente LÃ³pez', 'ARG', 'Buenos Aires', 288341);
INSERT INTO city (id, name, countrycode, district, population) VALUES (93, 'Berazategui', 'ARG', 'Buenos Aires', 276916);
INSERT INTO city (id, name, countrycode, district, population) VALUES (94, 'Corrientes', 'ARG', 'Corrientes', 258103);
INSERT INTO city (id, name, countrycode, district, population) VALUES (95, 'San Miguel', 'ARG', 'Buenos Aires', 248700);
INSERT INTO city (id, name, countrycode, district, population) VALUES (96, 'BahÃ­a Blanca', 'ARG', 'Buenos Aires', 239810);
INSERT INTO city (id, name, countrycode, district, population) VALUES (97, 'Esteban EcheverrÃ­a', 'ARG', 'Buenos Aires', 235760);
INSERT INTO city (id, name, countrycode, district, population) VALUES (98, 'Resistencia', 'ARG', 'Chaco', 229212);
INSERT INTO city (id, name, countrycode, district, population) VALUES (99, 'JosÃ© C. Paz', 'ARG', 'Buenos Aires', 221754);
INSERT INTO city (id, name, countrycode, district, population) VALUES (100, 'ParanÃ¡', 'ARG', 'Entre Rios', 207041);
INSERT INTO city (id, name, countrycode, district, population) VALUES (101, 'Godoy Cruz', 'ARG', 'Mendoza', 206998);
INSERT INTO city (id, name, countrycode, district, population) VALUES (102, 'Posadas', 'ARG', 'Misiones', 201273);
INSERT INTO city (id, name, countrycode, district, population) VALUES (103, 'GuaymallÃ©n', 'ARG', 'Mendoza', 200595);
INSERT INTO city (id, name, countrycode, district, population) VALUES (104, 'Santiago del Estero', 'ARG', 'Santiago del Estero', 189947);
INSERT INTO city (id, name, countrycode, district, population) VALUES (105, 'San Salvador de Jujuy', 'ARG', 'Jujuy', 178748);
INSERT INTO city (id, name, countrycode, district, population) VALUES (106, 'Hurlingham', 'ARG', 'Buenos Aires', 170028);
INSERT INTO city (id, name, countrycode, district, population) VALUES (107, 'NeuquÃ©n', 'ARG', 'NeuquÃ©n', 167296);
INSERT INTO city (id, name, countrycode, district, population) VALUES (108, 'ItuzaingÃ³', 'ARG', 'Buenos Aires', 158197);
INSERT INTO city (id, name, countrycode, district, population) VALUES (109, 'San Fernando', 'ARG', 'Buenos Aires', 153036);
INSERT INTO city (id, name, countrycode, district, population) VALUES (110, 'Formosa', 'ARG', 'Formosa', 147636);
INSERT INTO city (id, name, countrycode, district, population) VALUES (111, 'Las Heras', 'ARG', 'Mendoza', 145823);
INSERT INTO city (id, name, countrycode, district, population) VALUES (112, 'La Rioja', 'ARG', 'La Rioja', 138117);
INSERT INTO city (id, name, countrycode, district, population) VALUES (113, 'San Fernando del Valle de Cata', 'ARG', 'Catamarca', 134935);
INSERT INTO city (id, name, countrycode, district, population) VALUES (114, 'RÃ­o Cuarto', 'ARG', 'CÃ³rdoba', 134355);
INSERT INTO city (id, name, countrycode, district, population) VALUES (115, 'Comodoro Rivadavia', 'ARG', 'Chubut', 124104);
INSERT INTO city (id, name, countrycode, district, population) VALUES (116, 'Mendoza', 'ARG', 'Mendoza', 123027);
INSERT INTO city (id, name, countrycode, district, population) VALUES (117, 'San NicolÃ¡s de los Arroyos', 'ARG', 'Buenos Aires', 119302);
INSERT INTO city (id, name, countrycode, district, population) VALUES (118, 'San Juan', 'ARG', 'San Juan', 119152);
INSERT INTO city (id, name, countrycode, district, population) VALUES (119, 'Escobar', 'ARG', 'Buenos Aires', 116675);
INSERT INTO city (id, name, countrycode, district, population) VALUES (120, 'Concordia', 'ARG', 'Entre Rios', 116485);
INSERT INTO city (id, name, countrycode, district, population) VALUES (121, 'Pilar', 'ARG', 'Buenos Aires', 113428);
INSERT INTO city (id, name, countrycode, district, population) VALUES (122, 'San Luis', 'ARG', 'San Luis', 110136);
INSERT INTO city (id, name, countrycode, district, population) VALUES (123, 'Ezeiza', 'ARG', 'Buenos Aires', 99578);
INSERT INTO city (id, name, countrycode, district, population) VALUES (124, 'San Rafael', 'ARG', 'Mendoza', 94651);
INSERT INTO city (id, name, countrycode, district, population) VALUES (125, 'Tandil', 'ARG', 'Buenos Aires', 91101);
INSERT INTO city (id, name, countrycode, district, population) VALUES (126, 'Yerevan', 'ARM', 'Yerevan', 1248700);
INSERT INTO city (id, name, countrycode, district, population) VALUES (127, 'Gjumri', 'ARM', 'ÂŠirak', 211700);
INSERT INTO city (id, name, countrycode, district, population) VALUES (128, 'Vanadzor', 'ARM', 'Lori', 172700);
INSERT INTO city (id, name, countrycode, district, population) VALUES (129, 'Oranjestad', 'ABW', 'Â–', 29034);
INSERT INTO city (id, name, countrycode, district, population) VALUES (130, 'Sydney', 'AUS', 'New South Wales', 3276207);
INSERT INTO city (id, name, countrycode, district, population) VALUES (131, 'Melbourne', 'AUS', 'Victoria', 2865329);
INSERT INTO city (id, name, countrycode, district, population) VALUES (132, 'Brisbane', 'AUS', 'Queensland', 1291117);
INSERT INTO city (id, name, countrycode, district, population) VALUES (133, 'Perth', 'AUS', 'West Australia', 1096829);
INSERT INTO city (id, name, countrycode, district, population) VALUES (134, 'Adelaide', 'AUS', 'South Australia', 978100);
INSERT INTO city (id, name, countrycode, district, population) VALUES (135, 'Canberra', 'AUS', 'Capital Region', 322723);
INSERT INTO city (id, name, countrycode, district, population) VALUES (136, 'Gold Coast', 'AUS', 'Queensland', 311932);
INSERT INTO city (id, name, countrycode, district, population) VALUES (137, 'Newcastle', 'AUS', 'New South Wales', 270324);
INSERT INTO city (id, name, countrycode, district, population) VALUES (138, 'Central Coast', 'AUS', 'New South Wales', 227657);
INSERT INTO city (id, name, countrycode, district, population) VALUES (139, 'Wollongong', 'AUS', 'New South Wales', 219761);
INSERT INTO city (id, name, countrycode, district, population) VALUES (140, 'Hobart', 'AUS', 'Tasmania', 126118);
INSERT INTO city (id, name, countrycode, district, population) VALUES (141, 'Geelong', 'AUS', 'Victoria', 125382);
INSERT INTO city (id, name, countrycode, district, population) VALUES (142, 'Townsville', 'AUS', 'Queensland', 109914);
INSERT INTO city (id, name, countrycode, district, population) VALUES (143, 'Cairns', 'AUS', 'Queensland', 92273);
INSERT INTO city (id, name, countrycode, district, population) VALUES (144, 'Baku', 'AZE', 'Baki', 1787800);
INSERT INTO city (id, name, countrycode, district, population) VALUES (145, 'GÃ¤ncÃ¤', 'AZE', 'GÃ¤ncÃ¤', 299300);
INSERT INTO city (id, name, countrycode, district, population) VALUES (146, 'Sumqayit', 'AZE', 'Sumqayit', 283000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (147, 'MingÃ¤Ã§evir', 'AZE', 'MingÃ¤Ã§evir', 93900);
INSERT INTO city (id, name, countrycode, district, population) VALUES (148, 'Nassau', 'BHS', 'New Providence', 172000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (149, 'al-Manama', 'BHR', 'al-Manama', 148000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (150, 'Dhaka', 'BGD', 'Dhaka', 3612850);
INSERT INTO city (id, name, countrycode, district, population) VALUES (151, 'Chittagong', 'BGD', 'Chittagong', 1392860);
INSERT INTO city (id, name, countrycode, district, population) VALUES (152, 'Khulna', 'BGD', 'Khulna', 663340);
INSERT INTO city (id, name, countrycode, district, population) VALUES (153, 'Rajshahi', 'BGD', 'Rajshahi', 294056);
INSERT INTO city (id, name, countrycode, district, population) VALUES (154, 'Narayanganj', 'BGD', 'Dhaka', 202134);
INSERT INTO city (id, name, countrycode, district, population) VALUES (155, 'Rangpur', 'BGD', 'Rajshahi', 191398);
INSERT INTO city (id, name, countrycode, district, population) VALUES (156, 'Mymensingh', 'BGD', 'Dhaka', 188713);
INSERT INTO city (id, name, countrycode, district, population) VALUES (157, 'Barisal', 'BGD', 'Barisal', 170232);
INSERT INTO city (id, name, countrycode, district, population) VALUES (158, 'Tungi', 'BGD', 'Dhaka', 168702);
INSERT INTO city (id, name, countrycode, district, population) VALUES (159, 'Jessore', 'BGD', 'Khulna', 139710);
INSERT INTO city (id, name, countrycode, district, population) VALUES (160, 'Comilla', 'BGD', 'Chittagong', 135313);
INSERT INTO city (id, name, countrycode, district, population) VALUES (161, 'Nawabganj', 'BGD', 'Rajshahi', 130577);
INSERT INTO city (id, name, countrycode, district, population) VALUES (162, 'Dinajpur', 'BGD', 'Rajshahi', 127815);
INSERT INTO city (id, name, countrycode, district, population) VALUES (163, 'Bogra', 'BGD', 'Rajshahi', 120170);
INSERT INTO city (id, name, countrycode, district, population) VALUES (164, 'Sylhet', 'BGD', 'Sylhet', 117396);
INSERT INTO city (id, name, countrycode, district, population) VALUES (165, 'Brahmanbaria', 'BGD', 'Chittagong', 109032);
INSERT INTO city (id, name, countrycode, district, population) VALUES (166, 'Tangail', 'BGD', 'Dhaka', 106004);
INSERT INTO city (id, name, countrycode, district, population) VALUES (167, 'Jamalpur', 'BGD', 'Dhaka', 103556);
INSERT INTO city (id, name, countrycode, district, population) VALUES (168, 'Pabna', 'BGD', 'Rajshahi', 103277);
INSERT INTO city (id, name, countrycode, district, population) VALUES (169, 'Naogaon', 'BGD', 'Rajshahi', 101266);
INSERT INTO city (id, name, countrycode, district, population) VALUES (170, 'Sirajganj', 'BGD', 'Rajshahi', 99669);
INSERT INTO city (id, name, countrycode, district, population) VALUES (171, 'Narsinghdi', 'BGD', 'Dhaka', 98342);
INSERT INTO city (id, name, countrycode, district, population) VALUES (172, 'Saidpur', 'BGD', 'Rajshahi', 96777);
INSERT INTO city (id, name, countrycode, district, population) VALUES (173, 'Gazipur', 'BGD', 'Dhaka', 96717);
INSERT INTO city (id, name, countrycode, district, population) VALUES (174, 'Bridgetown', 'BRB', 'St Michael', 6070);
INSERT INTO city (id, name, countrycode, district, population) VALUES (175, 'Antwerpen', 'BEL', 'Antwerpen', 446525);
INSERT INTO city (id, name, countrycode, district, population) VALUES (176, 'Gent', 'BEL', 'East Flanderi', 224180);
INSERT INTO city (id, name, countrycode, district, population) VALUES (177, 'Charleroi', 'BEL', 'Hainaut', 200827);
INSERT INTO city (id, name, countrycode, district, population) VALUES (178, 'LiÃ¨ge', 'BEL', 'LiÃ¨ge', 185639);
INSERT INTO city (id, name, countrycode, district, population) VALUES (179, 'Bruxelles [Brussel]', 'BEL', 'Bryssel', 133859);
INSERT INTO city (id, name, countrycode, district, population) VALUES (180, 'Brugge', 'BEL', 'West Flanderi', 116246);
INSERT INTO city (id, name, countrycode, district, population) VALUES (181, 'Schaerbeek', 'BEL', 'Bryssel', 105692);
INSERT INTO city (id, name, countrycode, district, population) VALUES (182, 'Namur', 'BEL', 'Namur', 105419);
INSERT INTO city (id, name, countrycode, district, population) VALUES (183, 'Mons', 'BEL', 'Hainaut', 90935);
INSERT INTO city (id, name, countrycode, district, population) VALUES (184, 'Belize City', 'BLZ', 'Belize City', 55810);
INSERT INTO city (id, name, countrycode, district, population) VALUES (185, 'Belmopan', 'BLZ', 'Cayo', 7105);
INSERT INTO city (id, name, countrycode, district, population) VALUES (186, 'Cotonou', 'BEN', 'Atlantique', 536827);
INSERT INTO city (id, name, countrycode, district, population) VALUES (187, 'Porto-Novo', 'BEN', 'OuÃ©mÃ©', 194000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (188, 'Djougou', 'BEN', 'Atacora', 134099);
INSERT INTO city (id, name, countrycode, district, population) VALUES (189, 'Parakou', 'BEN', 'Borgou', 103577);
INSERT INTO city (id, name, countrycode, district, population) VALUES (190, 'Saint George', 'BMU', 'Saint GeorgeÂ´s', 1800);
INSERT INTO city (id, name, countrycode, district, population) VALUES (191, 'Hamilton', 'BMU', 'Hamilton', 1200);
INSERT INTO city (id, name, countrycode, district, population) VALUES (192, 'Thimphu', 'BTN', 'Thimphu', 22000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (193, 'Santa Cruz de la Sierra', 'BOL', 'Santa Cruz', 935361);
INSERT INTO city (id, name, countrycode, district, population) VALUES (194, 'La Paz', 'BOL', 'La Paz', 758141);
INSERT INTO city (id, name, countrycode, district, population) VALUES (195, 'El Alto', 'BOL', 'La Paz', 534466);
INSERT INTO city (id, name, countrycode, district, population) VALUES (196, 'Cochabamba', 'BOL', 'Cochabamba', 482800);
INSERT INTO city (id, name, countrycode, district, population) VALUES (197, 'Oruro', 'BOL', 'Oruro', 223553);
INSERT INTO city (id, name, countrycode, district, population) VALUES (198, 'Sucre', 'BOL', 'Chuquisaca', 178426);
INSERT INTO city (id, name, countrycode, district, population) VALUES (199, 'PotosÃ­', 'BOL', 'PotosÃ­', 140642);
INSERT INTO city (id, name, countrycode, district, population) VALUES (200, 'Tarija', 'BOL', 'Tarija', 125255);
INSERT INTO city (id, name, countrycode, district, population) VALUES (201, 'Sarajevo', 'BIH', 'Federaatio', 360000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (202, 'Banja Luka', 'BIH', 'Republika Srpska', 143079);
INSERT INTO city (id, name, countrycode, district, population) VALUES (203, 'Zenica', 'BIH', 'Federaatio', 96027);
INSERT INTO city (id, name, countrycode, district, population) VALUES (204, 'Gaborone', 'BWA', 'Gaborone', 213017);
INSERT INTO city (id, name, countrycode, district, population) VALUES (205, 'Francistown', 'BWA', 'Francistown', 101805);
INSERT INTO city (id, name, countrycode, district, population) VALUES (206, 'SÃ£o Paulo', 'BRA', 'SÃ£o Paulo', 9968485);
INSERT INTO city (id, name, countrycode, district, population) VALUES (207, 'Rio de Janeiro', 'BRA', 'Rio de Janeiro', 5598953);
INSERT INTO city (id, name, countrycode, district, population) VALUES (208, 'Salvador', 'BRA', 'Bahia', 2302832);
INSERT INTO city (id, name, countrycode, district, population) VALUES (209, 'Belo Horizonte', 'BRA', 'Minas Gerais', 2139125);
INSERT INTO city (id, name, countrycode, district, population) VALUES (210, 'Fortaleza', 'BRA', 'CearÃ¡', 2097757);
INSERT INTO city (id, name, countrycode, district, population) VALUES (211, 'BrasÃ­lia', 'BRA', 'Distrito Federal', 1969868);
INSERT INTO city (id, name, countrycode, district, population) VALUES (212, 'Curitiba', 'BRA', 'ParanÃ¡', 1584232);
INSERT INTO city (id, name, countrycode, district, population) VALUES (213, 'Recife', 'BRA', 'Pernambuco', 1378087);
INSERT INTO city (id, name, countrycode, district, population) VALUES (214, 'Porto Alegre', 'BRA', 'Rio Grande do Sul', 1314032);
INSERT INTO city (id, name, countrycode, district, population) VALUES (215, 'Manaus', 'BRA', 'Amazonas', 1255049);
INSERT INTO city (id, name, countrycode, district, population) VALUES (216, 'BelÃ©m', 'BRA', 'ParÃ¡', 1186926);
INSERT INTO city (id, name, countrycode, district, population) VALUES (217, 'Guarulhos', 'BRA', 'SÃ£o Paulo', 1095874);
INSERT INTO city (id, name, countrycode, district, population) VALUES (218, 'GoiÃ¢nia', 'BRA', 'GoiÃ¡s', 1056330);
INSERT INTO city (id, name, countrycode, district, population) VALUES (219, 'Campinas', 'BRA', 'SÃ£o Paulo', 950043);
INSERT INTO city (id, name, countrycode, district, population) VALUES (220, 'SÃ£o GonÃ§alo', 'BRA', 'Rio de Janeiro', 869254);
INSERT INTO city (id, name, countrycode, district, population) VALUES (221, 'Nova IguaÃ§u', 'BRA', 'Rio de Janeiro', 862225);
INSERT INTO city (id, name, countrycode, district, population) VALUES (222, 'SÃ£o LuÃ­s', 'BRA', 'MaranhÃ£o', 837588);
INSERT INTO city (id, name, countrycode, district, population) VALUES (223, 'MaceiÃ³', 'BRA', 'Alagoas', 786288);
INSERT INTO city (id, name, countrycode, district, population) VALUES (224, 'Duque de Caxias', 'BRA', 'Rio de Janeiro', 746758);
INSERT INTO city (id, name, countrycode, district, population) VALUES (225, 'SÃ£o Bernardo do Campo', 'BRA', 'SÃ£o Paulo', 723132);
INSERT INTO city (id, name, countrycode, district, population) VALUES (226, 'Teresina', 'BRA', 'PiauÃ­', 691942);
INSERT INTO city (id, name, countrycode, district, population) VALUES (227, 'Natal', 'BRA', 'Rio Grande do Norte', 688955);
INSERT INTO city (id, name, countrycode, district, population) VALUES (228, 'Osasco', 'BRA', 'SÃ£o Paulo', 659604);
INSERT INTO city (id, name, countrycode, district, population) VALUES (229, 'Campo Grande', 'BRA', 'Mato Grosso do Sul', 649593);
INSERT INTO city (id, name, countrycode, district, population) VALUES (230, 'Santo AndrÃ©', 'BRA', 'SÃ£o Paulo', 630073);
INSERT INTO city (id, name, countrycode, district, population) VALUES (231, 'JoÃ£o Pessoa', 'BRA', 'ParaÃ­ba', 584029);
INSERT INTO city (id, name, countrycode, district, population) VALUES (232, 'JaboatÃ£o dos Guararapes', 'BRA', 'Pernambuco', 558680);
INSERT INTO city (id, name, countrycode, district, population) VALUES (233, 'Contagem', 'BRA', 'Minas Gerais', 520801);
INSERT INTO city (id, name, countrycode, district, population) VALUES (234, 'SÃ£o JosÃ© dos Campos', 'BRA', 'SÃ£o Paulo', 515553);
INSERT INTO city (id, name, countrycode, district, population) VALUES (235, 'UberlÃ¢ndia', 'BRA', 'Minas Gerais', 487222);
INSERT INTO city (id, name, countrycode, district, population) VALUES (236, 'Feira de Santana', 'BRA', 'Bahia', 479992);
INSERT INTO city (id, name, countrycode, district, population) VALUES (237, 'RibeirÃ£o Preto', 'BRA', 'SÃ£o Paulo', 473276);
INSERT INTO city (id, name, countrycode, district, population) VALUES (238, 'Sorocaba', 'BRA', 'SÃ£o Paulo', 466823);
INSERT INTO city (id, name, countrycode, district, population) VALUES (239, 'NiterÃ³i', 'BRA', 'Rio de Janeiro', 459884);
INSERT INTO city (id, name, countrycode, district, population) VALUES (240, 'CuiabÃ¡', 'BRA', 'Mato Grosso', 453813);
INSERT INTO city (id, name, countrycode, district, population) VALUES (241, 'Juiz de Fora', 'BRA', 'Minas Gerais', 450288);
INSERT INTO city (id, name, countrycode, district, population) VALUES (242, 'Aracaju', 'BRA', 'Sergipe', 445555);
INSERT INTO city (id, name, countrycode, district, population) VALUES (243, 'SÃ£o JoÃ£o de Meriti', 'BRA', 'Rio de Janeiro', 440052);
INSERT INTO city (id, name, countrycode, district, population) VALUES (244, 'Londrina', 'BRA', 'ParanÃ¡', 432257);
INSERT INTO city (id, name, countrycode, district, population) VALUES (245, 'Joinville', 'BRA', 'Santa Catarina', 428011);
INSERT INTO city (id, name, countrycode, district, population) VALUES (246, 'Belford Roxo', 'BRA', 'Rio de Janeiro', 425194);
INSERT INTO city (id, name, countrycode, district, population) VALUES (247, 'Santos', 'BRA', 'SÃ£o Paulo', 408748);
INSERT INTO city (id, name, countrycode, district, population) VALUES (248, 'Ananindeua', 'BRA', 'ParÃ¡', 400940);
INSERT INTO city (id, name, countrycode, district, population) VALUES (249, 'Campos dos Goytacazes', 'BRA', 'Rio de Janeiro', 398418);
INSERT INTO city (id, name, countrycode, district, population) VALUES (250, 'MauÃ¡', 'BRA', 'SÃ£o Paulo', 375055);
INSERT INTO city (id, name, countrycode, district, population) VALUES (251, 'CarapicuÃ­ba', 'BRA', 'SÃ£o Paulo', 357552);
INSERT INTO city (id, name, countrycode, district, population) VALUES (252, 'Olinda', 'BRA', 'Pernambuco', 354732);
INSERT INTO city (id, name, countrycode, district, population) VALUES (253, 'Campina Grande', 'BRA', 'ParaÃ­ba', 352497);
INSERT INTO city (id, name, countrycode, district, population) VALUES (254, 'SÃ£o JosÃ© do Rio Preto', 'BRA', 'SÃ£o Paulo', 351944);
INSERT INTO city (id, name, countrycode, district, population) VALUES (255, 'Caxias do Sul', 'BRA', 'Rio Grande do Sul', 349581);
INSERT INTO city (id, name, countrycode, district, population) VALUES (256, 'Moji das Cruzes', 'BRA', 'SÃ£o Paulo', 339194);
INSERT INTO city (id, name, countrycode, district, population) VALUES (257, 'Diadema', 'BRA', 'SÃ£o Paulo', 335078);
INSERT INTO city (id, name, countrycode, district, population) VALUES (258, 'Aparecida de GoiÃ¢nia', 'BRA', 'GoiÃ¡s', 324662);
INSERT INTO city (id, name, countrycode, district, population) VALUES (259, 'Piracicaba', 'BRA', 'SÃ£o Paulo', 319104);
INSERT INTO city (id, name, countrycode, district, population) VALUES (260, 'Cariacica', 'BRA', 'EspÃ­rito Santo', 319033);
INSERT INTO city (id, name, countrycode, district, population) VALUES (261, 'Vila Velha', 'BRA', 'EspÃ­rito Santo', 318758);
INSERT INTO city (id, name, countrycode, district, population) VALUES (262, 'Pelotas', 'BRA', 'Rio Grande do Sul', 315415);
INSERT INTO city (id, name, countrycode, district, population) VALUES (263, 'Bauru', 'BRA', 'SÃ£o Paulo', 313670);
INSERT INTO city (id, name, countrycode, district, population) VALUES (264, 'Porto Velho', 'BRA', 'RondÃ´nia', 309750);
INSERT INTO city (id, name, countrycode, district, population) VALUES (265, 'Serra', 'BRA', 'EspÃ­rito Santo', 302666);
INSERT INTO city (id, name, countrycode, district, population) VALUES (266, 'Betim', 'BRA', 'Minas Gerais', 302108);
INSERT INTO city (id, name, countrycode, district, population) VALUES (267, 'JundÃ­aÃ­', 'BRA', 'SÃ£o Paulo', 296127);
INSERT INTO city (id, name, countrycode, district, population) VALUES (268, 'Canoas', 'BRA', 'Rio Grande do Sul', 294125);
INSERT INTO city (id, name, countrycode, district, population) VALUES (269, 'Franca', 'BRA', 'SÃ£o Paulo', 290139);
INSERT INTO city (id, name, countrycode, district, population) VALUES (270, 'SÃ£o Vicente', 'BRA', 'SÃ£o Paulo', 286848);
INSERT INTO city (id, name, countrycode, district, population) VALUES (271, 'MaringÃ¡', 'BRA', 'ParanÃ¡', 286461);
INSERT INTO city (id, name, countrycode, district, population) VALUES (272, 'Montes Claros', 'BRA', 'Minas Gerais', 286058);
INSERT INTO city (id, name, countrycode, district, population) VALUES (273, 'AnÃ¡polis', 'BRA', 'GoiÃ¡s', 282197);
INSERT INTO city (id, name, countrycode, district, population) VALUES (274, 'FlorianÃ³polis', 'BRA', 'Santa Catarina', 281928);
INSERT INTO city (id, name, countrycode, district, population) VALUES (275, 'PetrÃ³polis', 'BRA', 'Rio de Janeiro', 279183);
INSERT INTO city (id, name, countrycode, district, population) VALUES (276, 'Itaquaquecetuba', 'BRA', 'SÃ£o Paulo', 270874);
INSERT INTO city (id, name, countrycode, district, population) VALUES (277, 'VitÃ³ria', 'BRA', 'EspÃ­rito Santo', 270626);
INSERT INTO city (id, name, countrycode, district, population) VALUES (278, 'Ponta Grossa', 'BRA', 'ParanÃ¡', 268013);
INSERT INTO city (id, name, countrycode, district, population) VALUES (279, 'Rio Branco', 'BRA', 'Acre', 259537);
INSERT INTO city (id, name, countrycode, district, population) VALUES (280, 'Foz do IguaÃ§u', 'BRA', 'ParanÃ¡', 259425);
INSERT INTO city (id, name, countrycode, district, population) VALUES (281, 'MacapÃ¡', 'BRA', 'AmapÃ¡', 256033);
INSERT INTO city (id, name, countrycode, district, population) VALUES (282, 'IlhÃ©us', 'BRA', 'Bahia', 254970);
INSERT INTO city (id, name, countrycode, district, population) VALUES (283, 'VitÃ³ria da Conquista', 'BRA', 'Bahia', 253587);
INSERT INTO city (id, name, countrycode, district, population) VALUES (284, 'Uberaba', 'BRA', 'Minas Gerais', 249225);
INSERT INTO city (id, name, countrycode, district, population) VALUES (285, 'Paulista', 'BRA', 'Pernambuco', 248473);
INSERT INTO city (id, name, countrycode, district, population) VALUES (286, 'Limeira', 'BRA', 'SÃ£o Paulo', 245497);
INSERT INTO city (id, name, countrycode, district, population) VALUES (287, 'Blumenau', 'BRA', 'Santa Catarina', 244379);
INSERT INTO city (id, name, countrycode, district, population) VALUES (288, 'Caruaru', 'BRA', 'Pernambuco', 244247);
INSERT INTO city (id, name, countrycode, district, population) VALUES (289, 'SantarÃ©m', 'BRA', 'ParÃ¡', 241771);
INSERT INTO city (id, name, countrycode, district, population) VALUES (290, 'Volta Redonda', 'BRA', 'Rio de Janeiro', 240315);
INSERT INTO city (id, name, countrycode, district, population) VALUES (291, 'Novo Hamburgo', 'BRA', 'Rio Grande do Sul', 239940);
INSERT INTO city (id, name, countrycode, district, population) VALUES (292, 'Caucaia', 'BRA', 'CearÃ¡', 238738);
INSERT INTO city (id, name, countrycode, district, population) VALUES (293, 'Santa Maria', 'BRA', 'Rio Grande do Sul', 238473);
INSERT INTO city (id, name, countrycode, district, population) VALUES (294, 'Cascavel', 'BRA', 'ParanÃ¡', 237510);
INSERT INTO city (id, name, countrycode, district, population) VALUES (295, 'GuarujÃ¡', 'BRA', 'SÃ£o Paulo', 237206);
INSERT INTO city (id, name, countrycode, district, population) VALUES (296, 'RibeirÃ£o das Neves', 'BRA', 'Minas Gerais', 232685);
INSERT INTO city (id, name, countrycode, district, population) VALUES (297, 'Governador Valadares', 'BRA', 'Minas Gerais', 231724);
INSERT INTO city (id, name, countrycode, district, population) VALUES (298, 'TaubatÃ©', 'BRA', 'SÃ£o Paulo', 229130);
INSERT INTO city (id, name, countrycode, district, population) VALUES (299, 'Imperatriz', 'BRA', 'MaranhÃ£o', 224564);
INSERT INTO city (id, name, countrycode, district, population) VALUES (300, 'GravataÃ­', 'BRA', 'Rio Grande do Sul', 223011);
INSERT INTO city (id, name, countrycode, district, population) VALUES (301, 'Embu', 'BRA', 'SÃ£o Paulo', 222223);
INSERT INTO city (id, name, countrycode, district, population) VALUES (302, 'MossorÃ³', 'BRA', 'Rio Grande do Norte', 214901);
INSERT INTO city (id, name, countrycode, district, population) VALUES (303, 'VÃ¡rzea Grande', 'BRA', 'Mato Grosso', 214435);
INSERT INTO city (id, name, countrycode, district, population) VALUES (304, 'Petrolina', 'BRA', 'Pernambuco', 210540);
INSERT INTO city (id, name, countrycode, district, population) VALUES (305, 'Barueri', 'BRA', 'SÃ£o Paulo', 208426);
INSERT INTO city (id, name, countrycode, district, population) VALUES (306, 'ViamÃ£o', 'BRA', 'Rio Grande do Sul', 207557);
INSERT INTO city (id, name, countrycode, district, population) VALUES (307, 'Ipatinga', 'BRA', 'Minas Gerais', 206338);
INSERT INTO city (id, name, countrycode, district, population) VALUES (308, 'Juazeiro', 'BRA', 'Bahia', 201073);
INSERT INTO city (id, name, countrycode, district, population) VALUES (309, 'Juazeiro do Norte', 'BRA', 'CearÃ¡', 199636);
INSERT INTO city (id, name, countrycode, district, population) VALUES (310, 'TaboÃ£o da Serra', 'BRA', 'SÃ£o Paulo', 197550);
INSERT INTO city (id, name, countrycode, district, population) VALUES (311, 'SÃ£o JosÃ© dos Pinhais', 'BRA', 'ParanÃ¡', 196884);
INSERT INTO city (id, name, countrycode, district, population) VALUES (312, 'MagÃ©', 'BRA', 'Rio de Janeiro', 196147);
INSERT INTO city (id, name, countrycode, district, population) VALUES (313, 'Suzano', 'BRA', 'SÃ£o Paulo', 195434);
INSERT INTO city (id, name, countrycode, district, population) VALUES (314, 'SÃ£o Leopoldo', 'BRA', 'Rio Grande do Sul', 189258);
INSERT INTO city (id, name, countrycode, district, population) VALUES (315, 'MarÃ­lia', 'BRA', 'SÃ£o Paulo', 188691);
INSERT INTO city (id, name, countrycode, district, population) VALUES (316, 'SÃ£o Carlos', 'BRA', 'SÃ£o Paulo', 187122);
INSERT INTO city (id, name, countrycode, district, population) VALUES (317, 'SumarÃ©', 'BRA', 'SÃ£o Paulo', 186205);
INSERT INTO city (id, name, countrycode, district, population) VALUES (318, 'Presidente Prudente', 'BRA', 'SÃ£o Paulo', 185340);
INSERT INTO city (id, name, countrycode, district, population) VALUES (319, 'DivinÃ³polis', 'BRA', 'Minas Gerais', 185047);
INSERT INTO city (id, name, countrycode, district, population) VALUES (320, 'Sete Lagoas', 'BRA', 'Minas Gerais', 182984);
INSERT INTO city (id, name, countrycode, district, population) VALUES (321, 'Rio Grande', 'BRA', 'Rio Grande do Sul', 182222);
INSERT INTO city (id, name, countrycode, district, population) VALUES (322, 'Itabuna', 'BRA', 'Bahia', 182148);
INSERT INTO city (id, name, countrycode, district, population) VALUES (323, 'JequiÃ©', 'BRA', 'Bahia', 179128);
INSERT INTO city (id, name, countrycode, district, population) VALUES (324, 'Arapiraca', 'BRA', 'Alagoas', 178988);
INSERT INTO city (id, name, countrycode, district, population) VALUES (325, 'Colombo', 'BRA', 'ParanÃ¡', 177764);
INSERT INTO city (id, name, countrycode, district, population) VALUES (326, 'Americana', 'BRA', 'SÃ£o Paulo', 177409);
INSERT INTO city (id, name, countrycode, district, population) VALUES (327, 'Alvorada', 'BRA', 'Rio Grande do Sul', 175574);
INSERT INTO city (id, name, countrycode, district, population) VALUES (328, 'Araraquara', 'BRA', 'SÃ£o Paulo', 174381);
INSERT INTO city (id, name, countrycode, district, population) VALUES (329, 'ItaboraÃ­', 'BRA', 'Rio de Janeiro', 173977);
INSERT INTO city (id, name, countrycode, district, population) VALUES (330, 'Santa BÃ¡rbara dÂ´Oeste', 'BRA', 'SÃ£o Paulo', 171657);
INSERT INTO city (id, name, countrycode, district, population) VALUES (331, 'Nova Friburgo', 'BRA', 'Rio de Janeiro', 170697);
INSERT INTO city (id, name, countrycode, district, population) VALUES (332, 'JacareÃ­', 'BRA', 'SÃ£o Paulo', 170356);
INSERT INTO city (id, name, countrycode, district, population) VALUES (333, 'AraÃ§atuba', 'BRA', 'SÃ£o Paulo', 169303);
INSERT INTO city (id, name, countrycode, district, population) VALUES (334, 'Barra Mansa', 'BRA', 'Rio de Janeiro', 168953);
INSERT INTO city (id, name, countrycode, district, population) VALUES (335, 'Praia Grande', 'BRA', 'SÃ£o Paulo', 168434);
INSERT INTO city (id, name, countrycode, district, population) VALUES (336, 'MarabÃ¡', 'BRA', 'ParÃ¡', 167795);
INSERT INTO city (id, name, countrycode, district, population) VALUES (337, 'CriciÃºma', 'BRA', 'Santa Catarina', 167661);
INSERT INTO city (id, name, countrycode, district, population) VALUES (338, 'Boa Vista', 'BRA', 'Roraima', 167185);
INSERT INTO city (id, name, countrycode, district, population) VALUES (339, 'Passo Fundo', 'BRA', 'Rio Grande do Sul', 166343);
INSERT INTO city (id, name, countrycode, district, population) VALUES (340, 'Dourados', 'BRA', 'Mato Grosso do Sul', 164716);
INSERT INTO city (id, name, countrycode, district, population) VALUES (341, 'Santa Luzia', 'BRA', 'Minas Gerais', 164704);
INSERT INTO city (id, name, countrycode, district, population) VALUES (342, 'Rio Claro', 'BRA', 'SÃ£o Paulo', 163551);
INSERT INTO city (id, name, countrycode, district, population) VALUES (343, 'MaracanaÃº', 'BRA', 'CearÃ¡', 162022);
INSERT INTO city (id, name, countrycode, district, population) VALUES (344, 'Guarapuava', 'BRA', 'ParanÃ¡', 160510);
INSERT INTO city (id, name, countrycode, district, population) VALUES (345, 'RondonÃ³polis', 'BRA', 'Mato Grosso', 155115);
INSERT INTO city (id, name, countrycode, district, population) VALUES (346, 'SÃ£o JosÃ©', 'BRA', 'Santa Catarina', 155105);
INSERT INTO city (id, name, countrycode, district, population) VALUES (347, 'Cachoeiro de Itapemirim', 'BRA', 'EspÃ­rito Santo', 155024);
INSERT INTO city (id, name, countrycode, district, population) VALUES (348, 'NilÃ³polis', 'BRA', 'Rio de Janeiro', 153383);
INSERT INTO city (id, name, countrycode, district, population) VALUES (349, 'Itapevi', 'BRA', 'SÃ£o Paulo', 150664);
INSERT INTO city (id, name, countrycode, district, population) VALUES (350, 'Cabo de Santo Agostinho', 'BRA', 'Pernambuco', 149964);
INSERT INTO city (id, name, countrycode, district, population) VALUES (351, 'CamaÃ§ari', 'BRA', 'Bahia', 149146);
INSERT INTO city (id, name, countrycode, district, population) VALUES (352, 'Sobral', 'BRA', 'CearÃ¡', 146005);
INSERT INTO city (id, name, countrycode, district, population) VALUES (353, 'ItajaÃ­', 'BRA', 'Santa Catarina', 145197);
INSERT INTO city (id, name, countrycode, district, population) VALUES (354, 'ChapecÃ³', 'BRA', 'Santa Catarina', 144158);
INSERT INTO city (id, name, countrycode, district, population) VALUES (355, 'Cotia', 'BRA', 'SÃ£o Paulo', 140042);
INSERT INTO city (id, name, countrycode, district, population) VALUES (356, 'Lages', 'BRA', 'Santa Catarina', 139570);
INSERT INTO city (id, name, countrycode, district, population) VALUES (357, 'Ferraz de Vasconcelos', 'BRA', 'SÃ£o Paulo', 139283);
INSERT INTO city (id, name, countrycode, district, population) VALUES (358, 'Indaiatuba', 'BRA', 'SÃ£o Paulo', 135968);
INSERT INTO city (id, name, countrycode, district, population) VALUES (359, 'HortolÃ¢ndia', 'BRA', 'SÃ£o Paulo', 135755);
INSERT INTO city (id, name, countrycode, district, population) VALUES (360, 'Caxias', 'BRA', 'MaranhÃ£o', 133980);
INSERT INTO city (id, name, countrycode, district, population) VALUES (361, 'SÃ£o Caetano do Sul', 'BRA', 'SÃ£o Paulo', 133321);
INSERT INTO city (id, name, countrycode, district, population) VALUES (362, 'Itu', 'BRA', 'SÃ£o Paulo', 132736);
INSERT INTO city (id, name, countrycode, district, population) VALUES (363, 'Nossa Senhora do Socorro', 'BRA', 'Sergipe', 131351);
INSERT INTO city (id, name, countrycode, district, population) VALUES (364, 'ParnaÃ­ba', 'BRA', 'PiauÃ­', 129756);
INSERT INTO city (id, name, countrycode, district, population) VALUES (365, 'PoÃ§os de Caldas', 'BRA', 'Minas Gerais', 129683);
INSERT INTO city (id, name, countrycode, district, population) VALUES (366, 'TeresÃ³polis', 'BRA', 'Rio de Janeiro', 128079);
INSERT INTO city (id, name, countrycode, district, population) VALUES (367, 'Barreiras', 'BRA', 'Bahia', 127801);
INSERT INTO city (id, name, countrycode, district, population) VALUES (368, 'Castanhal', 'BRA', 'ParÃ¡', 127634);
INSERT INTO city (id, name, countrycode, district, population) VALUES (369, 'Alagoinhas', 'BRA', 'Bahia', 126820);
INSERT INTO city (id, name, countrycode, district, population) VALUES (370, 'Itapecerica da Serra', 'BRA', 'SÃ£o Paulo', 126672);
INSERT INTO city (id, name, countrycode, district, population) VALUES (371, 'Uruguaiana', 'BRA', 'Rio Grande do Sul', 126305);
INSERT INTO city (id, name, countrycode, district, population) VALUES (372, 'ParanaguÃ¡', 'BRA', 'ParanÃ¡', 126076);
INSERT INTO city (id, name, countrycode, district, population) VALUES (373, 'IbiritÃ©', 'BRA', 'Minas Gerais', 125982);
INSERT INTO city (id, name, countrycode, district, population) VALUES (374, 'Timon', 'BRA', 'MaranhÃ£o', 125812);
INSERT INTO city (id, name, countrycode, district, population) VALUES (375, 'LuziÃ¢nia', 'BRA', 'GoiÃ¡s', 125597);
INSERT INTO city (id, name, countrycode, district, population) VALUES (376, 'MacaÃ©', 'BRA', 'Rio de Janeiro', 125597);
INSERT INTO city (id, name, countrycode, district, population) VALUES (377, 'TeÃ³filo Otoni', 'BRA', 'Minas Gerais', 124489);
INSERT INTO city (id, name, countrycode, district, population) VALUES (378, 'Moji-GuaÃ§u', 'BRA', 'SÃ£o Paulo', 123782);
INSERT INTO city (id, name, countrycode, district, population) VALUES (379, 'Palmas', 'BRA', 'Tocantins', 121919);
INSERT INTO city (id, name, countrycode, district, population) VALUES (380, 'Pindamonhangaba', 'BRA', 'SÃ£o Paulo', 121904);
INSERT INTO city (id, name, countrycode, district, population) VALUES (381, 'Francisco Morato', 'BRA', 'SÃ£o Paulo', 121197);
INSERT INTO city (id, name, countrycode, district, population) VALUES (382, 'BagÃ©', 'BRA', 'Rio Grande do Sul', 120793);
INSERT INTO city (id, name, countrycode, district, population) VALUES (383, 'Sapucaia do Sul', 'BRA', 'Rio Grande do Sul', 120217);
INSERT INTO city (id, name, countrycode, district, population) VALUES (384, 'Cabo Frio', 'BRA', 'Rio de Janeiro', 119503);
INSERT INTO city (id, name, countrycode, district, population) VALUES (385, 'Itapetininga', 'BRA', 'SÃ£o Paulo', 119391);
INSERT INTO city (id, name, countrycode, district, population) VALUES (386, 'Patos de Minas', 'BRA', 'Minas Gerais', 119262);
INSERT INTO city (id, name, countrycode, district, population) VALUES (387, 'Camaragibe', 'BRA', 'Pernambuco', 118968);
INSERT INTO city (id, name, countrycode, district, population) VALUES (388, 'BraganÃ§a Paulista', 'BRA', 'SÃ£o Paulo', 116929);
INSERT INTO city (id, name, countrycode, district, population) VALUES (389, 'Queimados', 'BRA', 'Rio de Janeiro', 115020);
INSERT INTO city (id, name, countrycode, district, population) VALUES (390, 'AraguaÃ­na', 'BRA', 'Tocantins', 114948);
INSERT INTO city (id, name, countrycode, district, population) VALUES (391, 'Garanhuns', 'BRA', 'Pernambuco', 114603);
INSERT INTO city (id, name, countrycode, district, population) VALUES (392, 'VitÃ³ria de Santo AntÃ£o', 'BRA', 'Pernambuco', 113595);
INSERT INTO city (id, name, countrycode, district, population) VALUES (393, 'Santa Rita', 'BRA', 'ParaÃ­ba', 113135);
INSERT INTO city (id, name, countrycode, district, population) VALUES (394, 'Barbacena', 'BRA', 'Minas Gerais', 113079);
INSERT INTO city (id, name, countrycode, district, population) VALUES (395, 'Abaetetuba', 'BRA', 'ParÃ¡', 111258);
INSERT INTO city (id, name, countrycode, district, population) VALUES (396, 'JaÃº', 'BRA', 'SÃ£o Paulo', 109965);
INSERT INTO city (id, name, countrycode, district, population) VALUES (397, 'Lauro de Freitas', 'BRA', 'Bahia', 109236);
INSERT INTO city (id, name, countrycode, district, population) VALUES (398, 'Franco da Rocha', 'BRA', 'SÃ£o Paulo', 108964);
INSERT INTO city (id, name, countrycode, district, population) VALUES (399, 'Teixeira de Freitas', 'BRA', 'Bahia', 108441);
INSERT INTO city (id, name, countrycode, district, population) VALUES (400, 'Varginha', 'BRA', 'Minas Gerais', 108314);
INSERT INTO city (id, name, countrycode, district, population) VALUES (401, 'RibeirÃ£o Pires', 'BRA', 'SÃ£o Paulo', 108121);
INSERT INTO city (id, name, countrycode, district, population) VALUES (402, 'SabarÃ¡', 'BRA', 'Minas Gerais', 107781);
INSERT INTO city (id, name, countrycode, district, population) VALUES (403, 'Catanduva', 'BRA', 'SÃ£o Paulo', 107761);
INSERT INTO city (id, name, countrycode, district, population) VALUES (404, 'Rio Verde', 'BRA', 'GoiÃ¡s', 107755);
INSERT INTO city (id, name, countrycode, district, population) VALUES (405, 'Botucatu', 'BRA', 'SÃ£o Paulo', 107663);
INSERT INTO city (id, name, countrycode, district, population) VALUES (406, 'Colatina', 'BRA', 'EspÃ­rito Santo', 107354);
INSERT INTO city (id, name, countrycode, district, population) VALUES (407, 'Santa Cruz do Sul', 'BRA', 'Rio Grande do Sul', 106734);
INSERT INTO city (id, name, countrycode, district, population) VALUES (408, 'Linhares', 'BRA', 'EspÃ­rito Santo', 106278);
INSERT INTO city (id, name, countrycode, district, population) VALUES (409, 'Apucarana', 'BRA', 'ParanÃ¡', 105114);
INSERT INTO city (id, name, countrycode, district, population) VALUES (410, 'Barretos', 'BRA', 'SÃ£o Paulo', 104156);
INSERT INTO city (id, name, countrycode, district, population) VALUES (411, 'GuaratinguetÃ¡', 'BRA', 'SÃ£o Paulo', 103433);
INSERT INTO city (id, name, countrycode, district, population) VALUES (412, 'Cachoeirinha', 'BRA', 'Rio Grande do Sul', 103240);
INSERT INTO city (id, name, countrycode, district, population) VALUES (413, 'CodÃ³', 'BRA', 'MaranhÃ£o', 103153);
INSERT INTO city (id, name, countrycode, district, population) VALUES (414, 'JaraguÃ¡ do Sul', 'BRA', 'Santa Catarina', 102580);
INSERT INTO city (id, name, countrycode, district, population) VALUES (415, 'CubatÃ£o', 'BRA', 'SÃ£o Paulo', 102372);
INSERT INTO city (id, name, countrycode, district, population) VALUES (416, 'Itabira', 'BRA', 'Minas Gerais', 102217);
INSERT INTO city (id, name, countrycode, district, population) VALUES (417, 'Itaituba', 'BRA', 'ParÃ¡', 101320);
INSERT INTO city (id, name, countrycode, district, population) VALUES (418, 'Araras', 'BRA', 'SÃ£o Paulo', 101046);
INSERT INTO city (id, name, countrycode, district, population) VALUES (419, 'Resende', 'BRA', 'Rio de Janeiro', 100627);
INSERT INTO city (id, name, countrycode, district, population) VALUES (420, 'Atibaia', 'BRA', 'SÃ£o Paulo', 100356);
INSERT INTO city (id, name, countrycode, district, population) VALUES (421, 'Pouso Alegre', 'BRA', 'Minas Gerais', 100028);
INSERT INTO city (id, name, countrycode, district, population) VALUES (422, 'Toledo', 'BRA', 'ParanÃ¡', 99387);
INSERT INTO city (id, name, countrycode, district, population) VALUES (423, 'Crato', 'BRA', 'CearÃ¡', 98965);
INSERT INTO city (id, name, countrycode, district, population) VALUES (424, 'Passos', 'BRA', 'Minas Gerais', 98570);
INSERT INTO city (id, name, countrycode, district, population) VALUES (425, 'Araguari', 'BRA', 'Minas Gerais', 98399);
INSERT INTO city (id, name, countrycode, district, population) VALUES (426, 'SÃ£o JosÃ© de Ribamar', 'BRA', 'MaranhÃ£o', 98318);
INSERT INTO city (id, name, countrycode, district, population) VALUES (427, 'Pinhais', 'BRA', 'ParanÃ¡', 98198);
INSERT INTO city (id, name, countrycode, district, population) VALUES (428, 'SertÃ£ozinho', 'BRA', 'SÃ£o Paulo', 98140);
INSERT INTO city (id, name, countrycode, district, population) VALUES (429, 'Conselheiro Lafaiete', 'BRA', 'Minas Gerais', 97507);
INSERT INTO city (id, name, countrycode, district, population) VALUES (430, 'Paulo Afonso', 'BRA', 'Bahia', 97291);
INSERT INTO city (id, name, countrycode, district, population) VALUES (431, 'Angra dos Reis', 'BRA', 'Rio de Janeiro', 96864);
INSERT INTO city (id, name, countrycode, district, population) VALUES (432, 'EunÃ¡polis', 'BRA', 'Bahia', 96610);
INSERT INTO city (id, name, countrycode, district, population) VALUES (433, 'Salto', 'BRA', 'SÃ£o Paulo', 96348);
INSERT INTO city (id, name, countrycode, district, population) VALUES (434, 'Ourinhos', 'BRA', 'SÃ£o Paulo', 96291);
INSERT INTO city (id, name, countrycode, district, population) VALUES (435, 'Parnamirim', 'BRA', 'Rio Grande do Norte', 96210);
INSERT INTO city (id, name, countrycode, district, population) VALUES (436, 'Jacobina', 'BRA', 'Bahia', 96131);
INSERT INTO city (id, name, countrycode, district, population) VALUES (437, 'Coronel Fabriciano', 'BRA', 'Minas Gerais', 95933);
INSERT INTO city (id, name, countrycode, district, population) VALUES (438, 'Birigui', 'BRA', 'SÃ£o Paulo', 94685);
INSERT INTO city (id, name, countrycode, district, population) VALUES (439, 'TatuÃ­', 'BRA', 'SÃ£o Paulo', 93897);
INSERT INTO city (id, name, countrycode, district, population) VALUES (440, 'Ji-ParanÃ¡', 'BRA', 'RondÃ´nia', 93346);
INSERT INTO city (id, name, countrycode, district, population) VALUES (441, 'Bacabal', 'BRA', 'MaranhÃ£o', 93121);
INSERT INTO city (id, name, countrycode, district, population) VALUES (442, 'CametÃ¡', 'BRA', 'ParÃ¡', 92779);
INSERT INTO city (id, name, countrycode, district, population) VALUES (443, 'GuaÃ­ba', 'BRA', 'Rio Grande do Sul', 92224);
INSERT INTO city (id, name, countrycode, district, population) VALUES (444, 'SÃ£o LourenÃ§o da Mata', 'BRA', 'Pernambuco', 91999);
INSERT INTO city (id, name, countrycode, district, population) VALUES (445, 'Santana do Livramento', 'BRA', 'Rio Grande do Sul', 91779);
INSERT INTO city (id, name, countrycode, district, population) VALUES (446, 'Votorantim', 'BRA', 'SÃ£o Paulo', 91777);
INSERT INTO city (id, name, countrycode, district, population) VALUES (447, 'Campo Largo', 'BRA', 'ParanÃ¡', 91203);
INSERT INTO city (id, name, countrycode, district, population) VALUES (448, 'Patos', 'BRA', 'ParaÃ­ba', 90519);
INSERT INTO city (id, name, countrycode, district, population) VALUES (449, 'Ituiutaba', 'BRA', 'Minas Gerais', 90507);
INSERT INTO city (id, name, countrycode, district, population) VALUES (450, 'CorumbÃ¡', 'BRA', 'Mato Grosso do Sul', 90111);
INSERT INTO city (id, name, countrycode, district, population) VALUES (451, 'PalhoÃ§a', 'BRA', 'Santa Catarina', 89465);
INSERT INTO city (id, name, countrycode, district, population) VALUES (452, 'Barra do PiraÃ­', 'BRA', 'Rio de Janeiro', 89388);
INSERT INTO city (id, name, countrycode, district, population) VALUES (453, 'Bento GonÃ§alves', 'BRA', 'Rio Grande do Sul', 89254);
INSERT INTO city (id, name, countrycode, district, population) VALUES (454, 'PoÃ¡', 'BRA', 'SÃ£o Paulo', 89236);
INSERT INTO city (id, name, countrycode, district, population) VALUES (455, 'Ã�guas Lindas de GoiÃ¡s', 'BRA', 'GoiÃ¡s', 89200);
INSERT INTO city (id, name, countrycode, district, population) VALUES (456, 'London', 'GBR', 'England', 7285000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (457, 'Birmingham', 'GBR', 'England', 1013000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (458, 'Glasgow', 'GBR', 'Scotland', 619680);
INSERT INTO city (id, name, countrycode, district, population) VALUES (459, 'Liverpool', 'GBR', 'England', 461000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (460, 'Edinburgh', 'GBR', 'Scotland', 450180);
INSERT INTO city (id, name, countrycode, district, population) VALUES (461, 'Sheffield', 'GBR', 'England', 431607);
INSERT INTO city (id, name, countrycode, district, population) VALUES (462, 'Manchester', 'GBR', 'England', 430000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (463, 'Leeds', 'GBR', 'England', 424194);
INSERT INTO city (id, name, countrycode, district, population) VALUES (464, 'Bristol', 'GBR', 'England', 402000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (465, 'Cardiff', 'GBR', 'Wales', 321000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (466, 'Coventry', 'GBR', 'England', 304000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (467, 'Leicester', 'GBR', 'England', 294000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (468, 'Bradford', 'GBR', 'England', 289376);
INSERT INTO city (id, name, countrycode, district, population) VALUES (469, 'Belfast', 'GBR', 'North Ireland', 287500);
INSERT INTO city (id, name, countrycode, district, population) VALUES (470, 'Nottingham', 'GBR', 'England', 287000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (471, 'Kingston upon Hull', 'GBR', 'England', 262000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (472, 'Plymouth', 'GBR', 'England', 253000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (473, 'Stoke-on-Trent', 'GBR', 'England', 252000);
INSERT INTO city (id, name, countrycode, district, population) VALUES (474, 'Wolverhampton', 'GBR', 'England', 242000);

--
-- Add foreign key constraints.
--

ALTER TABLE country
    ADD CONSTRAINT country_capital_fkey FOREIGN KEY (capital) REFERENCES city(id);

ALTER TABLE countrylanguage
    ADD CONSTRAINT countrylanguage_countrycode_fkey FOREIGN KEY (countrycode) REFERENCES country(code);